image: python:3.8.6

stages:
  - code
  - security
  - publish-package
  - publish-docs

flake8:
  stage: code
  allow_failure: true
  script:
    - pip install flake8
    - flake8 . --count --select=E9,F63,F7,F82,E902 --show-source --statistics --max-line-length=120

lint:
  stage: code
  allow_failure: true
  script:
    - pip install -r requirements.txt
    - pip install lint
    - pylint notify

doctest:
  stage: code
  script:
    - python -m doctest -v notify/utils.py

pytest:
  stage: code
  script:
    - pip install -r requirements.txt
    - pip install pytest
    - pytest

publish package:
  stage: publish-package
  script:
    - pip install build
    - python -m build
    - pip install twine
    - twine upload --repository-url
      http://$PIPY_SERVER_HOST:$PYPI_SERVER_PORT
      --non-interactive -u $PYPI_USERNAME -p $PYPI_PASSWORD
      --disable-progress-bar dist/* --verbose
  only:
    - tags
  except:
    - /.*-dev$/

pages:
  stage: publish-docs
  only:
    - master
  script:
    - pip install mkdocs-material
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public
